# Generated by Django 3.1 on 2022-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positive_reviews', models.CharField(max_length=50)),
                ('negative_feedback', models.CharField(max_length=40)),
            ],
        ),
    ]
