# Generated by Django 3.1 on 2022-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('python', models.CharField(max_length=150)),
                ('java', models.CharField(max_length=100)),
                ('javascript', models.CharField(max_length=160)),
            ],
        ),
    ]
